### ISSUE TITLE
[SUGGESTION] CMS DETECTION FAILED 

### ISSUE THREAD

**Issue by N1gh7m4r3-N1dh** [Tuhinshubhra/CMSeeK#35]
Content:
    - CMSeeK Version: 1.1.0
    - Target: http://www.upsc.gov.in/
    - Probable CMS: Drupal

**Comment by Tuhinshubhra** [comment]
Detects just fine... check again.

**Comment by ScriptTiger** [comment]
The Indian government's UPSC (Union Public Service Commission) civil services website (http://www.upsc.gov.in/) was hacked and defaced and was temporarily taken offline, but has since been restored again. This was a website issue and not related to this repo.

**Comment by N1gh7m4r3-N1dh** [comment]
@ScriptTiger well while other scanners were detecting even when whole drupal configurations were compressed as an backup CMSeeK wasn't that's why i opened this up

**Comment by ScriptTiger** [comment]
Understood, @N1gh7m4r3-N1dh. That is much needed context for @Tuhinshubhra to work with. I think the actual issue here would be an enhancement request to add a new detection method for Drupal that can still detect the CMS even when it is in such a state.

The only way @Tuhinshubhra can proceed with this now is if you provide another Drupal website that is currently in the same state that has this issue, as nothing can be modeled or tested without it. It may also be helpful to provide another scanner tool you used that was successful that he can look at to extract how it signatures Drupal.

If someone else from the community has Drupal expertise and can create a PR for this, it may help avoid hunting for another Drupal site that is down.

**Comment by Tuhinshubhra** [comment]
Exactly... anyways no passive detection is possible while the site is in this state atleast not without any other information.

**Comment by Tuhinshubhra** [comment]
Anyways it works just fine

![selection_079](https://user-images.githubusercontent.com/28696468/45362302-2018a800-b5f2-11e8-8553-c04eff8da284.png)
